# DO NOT CHANGE, this value is used for internal plugin use only
Version: ${project.version}
# #################################################################### #
#                                                                      #
#                              Config.yml                              #
#                                                                      #
# #################################################################### #

# Enable debug mode
# Enabling this may result in your console being spammed with message about the plugin
# Only enable this if you want to learn more about the plugin, or are told to by support staff
Debug Mode: false # Defaults to false

# Set this to true if you want to use Vault in the plugin, this enables group based hooks
Vault hook: true

# Set this to true if you want to use PlaceholderAPI in the plugin
PAPI hook: true

# Set PAPI hook to true to use all the PlaceholderAPI placeholders
# in the messages

# These are the Placeholders provided by the plugin
Placeholders:
  Prefix: "&aTardisDev &8|"
  Error: "&cError &8|"
  Success: "&aSuccess &8|"
  Plugin Name: "&bHoverStats"
  Command Name: "HoverStats"
  Placeholder Filler: "0" # Set the default placeholder for any placeholders that are empty or equal "null"

# #################################################################### #
#                         List of placeholders                         #
# #################################################################### #
#                              Global                                  #
#                      ######################                          #
#                                                                      #
#                    Prefix       -       %prefix%                     #
#                     Error       -       %error%                      #
#                   Success       -       %success%                    #
#               Plugin Name       -       %pluginname%                 #
#              Command Name       -       %cmdName%                    #
#                    Player       -       %player%                     #
#                                                                      #
# #################################################################### #
#                           * Disclaimer *                             #
#                  Player may not work for certain                     #
#                              messages                                #
# #################################################################### #
#                                Chat                                  #
#                      ######################                          #
#                                                                      #
#       Previous Formatting       -       %prev-format%                #
#                                                                      #
# #################################################################### #
#                              * Note *                                #
#       Any placeholders in the chat section can only be used          #
#     within the 'Chat Formatting.Format' section of the config        #
# #################################################################### #

# Set the priority at which the chat event will run. Setting this can fix
# Compatibility issues with other plugins
#
# Note: You can find a list of event priorities at the link below:
# https://bukkit.fandom.com/wiki/Event_API_Reference#Event_Priorities
#
# Note: After changing this value, the server must be reloaded/restarted
Chat Event Priority: HIGH # Defaults to HIGH
Join Event Priority: HIGH # Defaults to HIGH
Quit Event Priority: HIGH # Defaults to HIGH

# Set all the different hex patterns you want to support in your chat
#
# Note: By default there is already one hex pattern that the plugin knows
# that hex pattern is the standard (#ffffff) pattern. No need to add that one
# to the list.
#
# Disclaimer: The hex patterns are checked sequentially meaning that the hex
# pattern that is on the top is checked first, then the next pattern and so
# on and so forth. If a hex code isn't working for whatever reason, try to add
# it to the top of the list and try again
Hex Patterns:
  # The default names for each of the hex codes is purely for aesthetics
  "<#ffffff>": # Set a unique name for the hex code
    Prefix: "<#" # Set what prefix the plugin should look for
    Suffix: ">" # Set the suffix that the plugin should look for

  "&#ffffff":
    Prefix: "&#"
    Suffix: ""

# Set the global date format
Date Format: "MM/dd/yy hh:mm:ss"

Formatting:
  # Setting this to false will make it so that either another plugin or default
  # minecraft will take control over the server's join messages. Setting this
  # to true will use the formatting below
  Use Join Formatting: true

  # Setting this to false will make it so that either another plugin or default
  # minecraft will take control over the server's leave messages. Setting this
  # to true will use the formatting below
  Use Quit Formatting: true


  Chat Formatting:
    # Setting this to true will make it so that only people who have the permission
    # 'hoverstats.chat.view' can view the hover able message
    #
    # Please note that this will make it so ONLY people with this permission are
    # able to view the hover able message
    Require Permission: false
    # Setting this to false will make it so that another plugin will take control
    # of the chat. Setting this to true will use the formatting below.
    #
    # Please note that this may cause the entire message to be taken over by
    # HoverStats. This is the case if you are using Luck Perms Chat (LPC) which
    # doesn't abide by Minecraft's chat formatting standards.
    Use Formatting: true
    # Setting this to false will make it so that you can use the chat formatting
    # from HoverStats instead of Luck Perms Chat (LPC). This shouldn't be changed
    # as if you have LPC you are more than likely planing to use it, and if you
    # aren't it should be removed.
    Override LPC: true

Hover Blacklist:
  # Define groups that are not able to send any hover messages
  Groups:
    - admin
  # Define users that are not able to send any hover messages
  Users:
    - Notch


# #################################################################### #
#                                                                      #
#                               Messages                               #
#                                                                      #
# #################################################################### #
Messages:
  System Messages:
    Success:
      PAPI Hook: "&aFound PlaceholderAPI, hooking into it."
      Vault Hook: "&aFound Vault, hooking into it."
      Reloaded: "%success% %pluginname%'s &7config has successfully reloaded!"

    Error:
      PAPI Hook: "&cCouldn't find PlaceholderAPI, any placeholders from PAPI will no longer work."
      Vault Hook: "&cCouldn't find Vault, permission based commands/placeholders will not work until vault is installed."
      No Permissions: "%error% &7You don't have permission to run this command!"

  # Default help message, you can change this if you want
  Help:
    - ""
    - "&7&l&m⎯⎯⎯⎯⎯⎯&r &a&l%pluginname% Help &r&7&l&m⎯⎯⎯⎯⎯⎯&r"
    - "&a/%cmdName% &7- Shows this message."
    - "&a/%cmdName% help &7- Shows this message."
    - "&a/%cmdName% reload &7- Reload's %pluginname%'s config."
    - "&7&l&m⎯⎯⎯⎯⎯⎯&r &a&l%pluginname% Help &r&7&l&m⎯⎯⎯⎯⎯⎯&r"
    - ""